### ISSUE TITLE
How to define time of an audio

### ISSUE THREAD

**Issue by huutuongtu** [haoheliu/AudioLDM-training-finetuning#13]
Thank you for your excellent work!

I have a question about how to define the exact time of audio when inferring. For example, in the sample code of audioldm2 huggingface, I see the parameter audio_length_in_s.

**Comment by haoheliu** [comment]
Some parameters in the training YAML config file might related to your question, such as `duration` parameter in https://github.com/haoheliu/AudioLDM-training-finetuning/blob/main/audioldm_train/config/2023_08_23_reproduce_audioldm/audioldm_crossattn_flant5.yaml
