### ISSUE TITLE
Fatal issue occurred during fine-tuning.

### ISSUE THREAD

**Issue by Ask-sola** [haoheliu/AudioLDM-training-finetuning#43]
I followed the normal procedure to fine-tune the program; however, I encountered an inexplicable error. I couldn't even find where the program calls the get_sample function, yet it is indeed being called and causing an error.
![image](https://github.com/user-attachments/assets/027d41b2-b1e9-4e8d-87b0-9a8322f487cc)
![image](https://github.com/user-attachments/assets/90633785-2649-466c-b72b-f7cac88f11fb)

**Comment by Ask-sola** [comment]
I checked the code and found that the problem is here.
![image](https://github.com/user-attachments/assets/10c7742b-7f71-402f-8806-ae675545f5b7)
I suspect the issue is caused by the environment settings. However, how should I configure it?

**Comment by Ask-sola** [comment]
本质上就是这个问题：
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR

**Comment by Ask-sola** [comment]
Essentially, that's the issue：RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR

**Comment by Ask-sola** [comment]
It was found out that it was caused by insufficient GPU memory

**Comment by Adrian-Makcimus** [comment]
How much GPU memory did you need? I am running into the same issue

**Comment by LOVEANDNINENINE** [comment]
The same issues……
